// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorkoutTracker.Infrastructure.Data;

#nullable disable

namespace WorkoutTracker.Infrastructure.Data.Migrations
{
    [DbContext(typeof(WorkoutTrackerDbContext))]
    [Migration("20260427093329_AddEffortToLoggedExercise")]
    partial class AddEffortToLoggedExercise
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("workout_tracker")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorkoutTracker.Infrastructure.Data.Models.Exercise", b =>
                {
                    b.Property<Guid>("ExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("ExerciseId")
                        .HasName("pk_exercises");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_exercises_name");

                    b.ToTable("exercises", "workout_tracker", t =>
                        {
                            t.HasCheckConstraint("ck_exercises_name_length", "length(name) <= 150");
                        });
                });

            modelBuilder.Entity("WorkoutTracker.Infrastructure.Data.Models.ExerciseMuscle", b =>
                {
                    b.Property<Guid>("ExerciseMuscleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_muscle_id");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<Guid>("MuscleId")
                        .HasColumnType("uuid")
                        .HasColumnName("muscle_id");

                    b.HasKey("ExerciseMuscleId")
                        .HasName("pk_exercise_muscles");

                    b.HasIndex("MuscleId")
                        .HasDatabaseName("ix_exercise_muscles_muscle_id");

                    b.HasIndex("ExerciseId", "MuscleId")
                        .IsUnique()
                        .HasDatabaseName("ix_exercise_muscles_exercise_id_muscle_id");

                    b.ToTable("exercise_muscles", "workout_tracker");
                });

            modelBuilder.Entity("WorkoutTracker.Infrastructure.Data.Models.LoggedExercise", b =>
                {
                    b.Property<Guid>("LoggedExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("logged_exercise_id");

                    b.Property<int?>("Effort")
                        .HasColumnType("integer")
                        .HasColumnName("effort");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<int?>("LoggedReps")
                        .HasColumnType("integer")
                        .HasColumnName("logged_reps");

                    b.Property<string>("LoggedWeight")
                        .HasColumnType("text")
                        .HasColumnName("logged_weight");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("WorkoutSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_session_id");

                    b.HasKey("LoggedExerciseId")
                        .HasName("pk_logged_exercises");

                    b.HasIndex("ExerciseId")
                        .HasDatabaseName("ix_logged_exercises_exercise_id");

                    b.HasIndex("WorkoutSessionId")
                        .HasDatabaseName("ix_logged_exercises_workout_session_id");

                    b.ToTable("logged_exercises", "workout_tracker", t =>
                        {
                            t.HasCheckConstraint("ck_logged_exercise_effort_range", "effort IS NULL OR (effort >= 1 AND effort <= 10)");
                        });
                });

            modelBuilder.Entity("WorkoutTracker.Infrastructure.Data.Models.Muscle", b =>
                {
                    b.Property<Guid>("MuscleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("muscle_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("MuscleId")
                        .HasName("pk_muscles");

                    b.ToTable("muscles", "workout_tracker");

                    b.HasData(
                        new
                        {
                            MuscleId = new Guid("a1000000-0000-0000-0000-00000000000c"),
                            Name = "Adductors"
                        },
                        new
                        {
                            MuscleId = new Guid("a1000000-0000-0000-0000-000000000001"),
                            Name = "Back"
                        },
                        new
                        {
                            MuscleId = new Guid("a1000000-0000-0000-0000-000000000002"),
                            Name = "Biceps"
                        },
                        new
                        {
                            MuscleId = new Guid("a1000000-0000-0000-0000-000000000003"),
                            Name = "Calves"
                        },
                        new
                        {
                            MuscleId = new Guid("a1000000-0000-0000-0000-000000000004"),
                            Name = "Chest"
                        },
                        new
                        {
                            MuscleId = new Guid("a1000000-0000-0000-0000-000000000005"),
                            Name = "Core"
                        },
                        new
                        {
                            MuscleId = new Guid("a1000000-0000-0000-0000-000000000006"),
                            Name = "Forearms"
                        },
                        new
                        {
                            MuscleId = new Guid("a1000000-0000-0000-0000-000000000007"),
                            Name = "Glutes"
                        },
                        new
                        {
                            MuscleId = new Guid("a1000000-0000-0000-0000-000000000008"),
                            Name = "Hamstrings"
                        },
                        new
                        {
                            MuscleId = new Guid("a1000000-0000-0000-0000-000000000009"),
                            Name = "Quads"
                        },
                        new
                        {
                            MuscleId = new Guid("a1000000-0000-0000-0000-00000000000a"),
                            Name = "Shoulders"
                        },
                        new
                        {
                            MuscleId = new Guid("a1000000-0000-0000-0000-00000000000b"),
                            Name = "Triceps"
                        });
                });

            modelBuilder.Entity("WorkoutTracker.Infrastructure.Data.Models.PlannedWorkout", b =>
                {
                    b.Property<Guid>("PlannedWorkoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("planned_workout_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("PlannedWorkoutId")
                        .HasName("pk_planned_workouts");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_planned_workouts_name");

                    b.ToTable("planned_workouts", "workout_tracker", t =>
                        {
                            t.HasCheckConstraint("ck_planned_workouts_name_length", "length(name) <= 150");
                        });
                });

            modelBuilder.Entity("WorkoutTracker.Infrastructure.Data.Models.PlannedWorkoutExercise", b =>
                {
                    b.Property<Guid>("PlannedWorkoutExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("planned_workout_exercise_id");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<Guid>("PlannedWorkoutId")
                        .HasColumnType("uuid")
                        .HasColumnName("planned_workout_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<string>("TargetReps")
                        .HasColumnType("text")
                        .HasColumnName("target_reps");

                    b.Property<string>("TargetWeight")
                        .HasColumnType("text")
                        .HasColumnName("target_weight");

                    b.HasKey("PlannedWorkoutExerciseId")
                        .HasName("pk_planned_workout_exercises");

                    b.HasIndex("ExerciseId")
                        .HasDatabaseName("ix_planned_workout_exercises_exercise_id");

                    b.HasIndex("PlannedWorkoutId", "ExerciseId")
                        .IsUnique()
                        .HasDatabaseName("ix_planned_workout_exercises_planned_workout_id_exercise_id");

                    b.ToTable("planned_workout_exercises", "workout_tracker");
                });

            modelBuilder.Entity("WorkoutTracker.Infrastructure.Data.Models.Workout", b =>
                {
                    b.Property<Guid>("WorkoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("workout_id");

                    b.Property<DateOnly>("WorkoutDate")
                        .HasColumnType("date")
                        .HasColumnName("workout_date");

                    b.Property<Guid>("WorkoutTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_type_id");

                    b.HasKey("WorkoutId")
                        .HasName("pk_workouts");

                    b.HasIndex("WorkoutTypeId")
                        .HasDatabaseName("ix_workouts_workout_type_id");

                    b.ToTable("workouts", "workout_tracker");
                });

            modelBuilder.Entity("WorkoutTracker.Infrastructure.Data.Models.WorkoutExercise", b =>
                {
                    b.Property<Guid>("WorkoutExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("workout_exercise_id");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<int?>("Reps")
                        .HasColumnType("integer")
                        .HasColumnName("reps");

                    b.Property<int?>("Sets")
                        .HasColumnType("integer")
                        .HasColumnName("sets");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("numeric")
                        .HasColumnName("weight");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_id");

                    b.HasKey("WorkoutExerciseId")
                        .HasName("pk_workout_exercises");

                    b.HasIndex("ExerciseId")
                        .HasDatabaseName("ix_workout_exercises_exercise_id");

                    b.HasIndex("WorkoutId")
                        .HasDatabaseName("ix_workout_exercises_workout_id");

                    b.ToTable("workout_exercises", "workout_tracker");
                });

            modelBuilder.Entity("WorkoutTracker.Infrastructure.Data.Models.WorkoutSession", b =>
                {
                    b.Property<Guid>("WorkoutSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("workout_session_id");

                    b.Property<DateTime>("CompletedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("PlannedWorkoutId")
                        .HasColumnType("uuid")
                        .HasColumnName("planned_workout_id");

                    b.Property<string>("WorkoutName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("workout_name");

                    b.HasKey("WorkoutSessionId")
                        .HasName("pk_workout_sessions");

                    b.HasIndex("PlannedWorkoutId")
                        .HasDatabaseName("ix_workout_sessions_planned_workout_id");

                    b.ToTable("workout_sessions", "workout_tracker");
                });

            modelBuilder.Entity("WorkoutTracker.Infrastructure.Data.Models.WorkoutType", b =>
                {
                    b.Property<Guid>("WorkoutTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("workout_type_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("WorkoutTypeId")
                        .HasName("pk_workout_types");

                    b.ToTable("workout_types", "workout_tracker");
                });

            modelBuilder.Entity("WorkoutTracker.Infrastructure.Data.Models.ExerciseMuscle", b =>
                {
                    b.HasOne("WorkoutTracker.Infrastructure.Data.Models.Exercise", "Exercise")
                        .WithMany("ExerciseMuscles")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exercise_muscles_exercises_exercise_id");

                    b.HasOne("WorkoutTracker.Infrastructure.Data.Models.Muscle", "Muscle")
                        .WithMany("ExerciseMuscles")
                        .HasForeignKey("MuscleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exercise_muscles_muscles_muscle_id");

                    b.Navigation("Exercise");

                    b.Navigation("Muscle");
                });

            modelBuilder.Entity("WorkoutTracker.Infrastructure.Data.Models.LoggedExercise", b =>
                {
                    b.HasOne("WorkoutTracker.Infrastructure.Data.Models.Exercise", "Exercise")
                        .WithMany("LoggedExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_logged_exercises_exercises_exercise_id");

                    b.HasOne("WorkoutTracker.Infrastructure.Data.Models.WorkoutSession", "WorkoutSession")
                        .WithMany("LoggedExercises")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_logged_exercises_workout_sessions_workout_session_id");

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("WorkoutTracker.Infrastructure.Data.Models.PlannedWorkoutExercise", b =>
                {
                    b.HasOne("WorkoutTracker.Infrastructure.Data.Models.Exercise", "Exercise")
                        .WithMany("PlannedWorkoutExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_planned_workout_exercises_exercises_exercise_id");

                    b.HasOne("WorkoutTracker.Infrastructure.Data.Models.PlannedWorkout", "PlannedWorkout")
                        .WithMany("Exercises")
                        .HasForeignKey("PlannedWorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_planned_workout_exercises_planned_workouts_planned_workout_");

                    b.Navigation("Exercise");

                    b.Navigation("PlannedWorkout");
                });

            modelBuilder.Entity("WorkoutTracker.Infrastructure.Data.Models.Workout", b =>
                {
                    b.HasOne("WorkoutTracker.Infrastructure.Data.Models.WorkoutType", "WorkoutType")
                        .WithMany("Workouts")
                        .HasForeignKey("WorkoutTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workouts_workout_types_workout_type_id");

                    b.Navigation("WorkoutType");
                });

            modelBuilder.Entity("WorkoutTracker.Infrastructure.Data.Models.WorkoutExercise", b =>
                {
                    b.HasOne("WorkoutTracker.Infrastructure.Data.Models.Exercise", "Exercise")
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workout_exercises_exercises_exercise_id");

                    b.HasOne("WorkoutTracker.Infrastructure.Data.Models.Workout", "Workout")
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workout_exercises_workouts_workout_id");

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("WorkoutTracker.Infrastructure.Data.Models.WorkoutSession", b =>
                {
                    b.HasOne("WorkoutTracker.Infrastructure.Data.Models.PlannedWorkout", "PlannedWorkout")
                        .WithMany("Sessions")
                        .HasForeignKey("PlannedWorkoutId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_workout_sessions_planned_workouts_planned_workout_id");

                    b.Navigation("PlannedWorkout");
                });

            modelBuilder.Entity("WorkoutTracker.Infrastructure.Data.Models.Exercise", b =>
                {
                    b.Navigation("ExerciseMuscles");

                    b.Navigation("LoggedExercises");

                    b.Navigation("PlannedWorkoutExercises");

                    b.Navigation("WorkoutExercises");
                });

            modelBuilder.Entity("WorkoutTracker.Infrastructure.Data.Models.Muscle", b =>
                {
                    b.Navigation("ExerciseMuscles");
                });

            modelBuilder.Entity("WorkoutTracker.Infrastructure.Data.Models.PlannedWorkout", b =>
                {
                    b.Navigation("Exercises");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("WorkoutTracker.Infrastructure.Data.Models.Workout", b =>
                {
                    b.Navigation("WorkoutExercises");
                });

            modelBuilder.Entity("WorkoutTracker.Infrastructure.Data.Models.WorkoutSession", b =>
                {
                    b.Navigation("LoggedExercises");
                });

            modelBuilder.Entity("WorkoutTracker.Infrastructure.Data.Models.WorkoutType", b =>
                {
                    b.Navigation("Workouts");
                });
#pragma warning restore 612, 618
        }
    }
}
