// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorkoutTracker.Infrastructure.Data;

#nullable disable

namespace WorkoutTracker.Infrastructure.Data.Migrations
{
    [DbContext(typeof(WorkoutTrackerDbContext))]
    partial class WorkoutTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("workout_tracker")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorkoutTracker.Infrastructure.Data.Models.Exercise", b =>
                {
                    b.Property<Guid>("ExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("ExerciseId")
                        .HasName("pk_exercises");

                    b.ToTable("exercises", "workout_tracker");
                });

            modelBuilder.Entity("WorkoutTracker.Infrastructure.Data.Models.Workout", b =>
                {
                    b.Property<Guid>("WorkoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("workout_id");

                    b.Property<DateOnly>("WorkoutDate")
                        .HasColumnType("date")
                        .HasColumnName("workout_date");

                    b.Property<Guid>("WorkoutTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_type_id");

                    b.HasKey("WorkoutId")
                        .HasName("pk_workouts");

                    b.HasIndex("WorkoutTypeId")
                        .HasDatabaseName("ix_workouts_workout_type_id");

                    b.ToTable("workouts", "workout_tracker");
                });

            modelBuilder.Entity("WorkoutTracker.Infrastructure.Data.Models.WorkoutExercise", b =>
                {
                    b.Property<Guid>("WorkoutExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("workout_exercise_id");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<int?>("Reps")
                        .HasColumnType("integer")
                        .HasColumnName("reps");

                    b.Property<int?>("Sets")
                        .HasColumnType("integer")
                        .HasColumnName("sets");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("numeric")
                        .HasColumnName("weight");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_id");

                    b.HasKey("WorkoutExerciseId")
                        .HasName("pk_workout_exercises");

                    b.HasIndex("ExerciseId")
                        .HasDatabaseName("ix_workout_exercises_exercise_id");

                    b.HasIndex("WorkoutId")
                        .HasDatabaseName("ix_workout_exercises_workout_id");

                    b.ToTable("workout_exercises", "workout_tracker");
                });

            modelBuilder.Entity("WorkoutTracker.Infrastructure.Data.Models.WorkoutType", b =>
                {
                    b.Property<Guid>("WorkoutTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("workout_type_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("WorkoutTypeId")
                        .HasName("pk_workout_types");

                    b.ToTable("workout_types", "workout_tracker");
                });

            modelBuilder.Entity("WorkoutTracker.Infrastructure.Data.Models.Workout", b =>
                {
                    b.HasOne("WorkoutTracker.Infrastructure.Data.Models.WorkoutType", "WorkoutType")
                        .WithMany("Workouts")
                        .HasForeignKey("WorkoutTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workouts_workout_types_workout_type_id");

                    b.Navigation("WorkoutType");
                });

            modelBuilder.Entity("WorkoutTracker.Infrastructure.Data.Models.WorkoutExercise", b =>
                {
                    b.HasOne("WorkoutTracker.Infrastructure.Data.Models.Exercise", "Exercise")
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workout_exercises_exercises_exercise_id");

                    b.HasOne("WorkoutTracker.Infrastructure.Data.Models.Workout", "Workout")
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workout_exercises_workouts_workout_id");

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("WorkoutTracker.Infrastructure.Data.Models.Exercise", b =>
                {
                    b.Navigation("WorkoutExercises");
                });

            modelBuilder.Entity("WorkoutTracker.Infrastructure.Data.Models.Workout", b =>
                {
                    b.Navigation("WorkoutExercises");
                });

            modelBuilder.Entity("WorkoutTracker.Infrastructure.Data.Models.WorkoutType", b =>
                {
                    b.Navigation("Workouts");
                });
#pragma warning restore 612, 618
        }
    }
}
